[package]
name = "linux-discord-rich-presence"
description = "Customize Discord Rich Presence with shell hooks."
authors = ["trickybestia <trickybestia@gmail.com>"]
version = "0.1.0"
edition = "2018"

[profile.release]
lto = true
codegen-units = 1
panic = 'unwind'

[dependencies]
discord-rich-presence = "^0.1"
clap = "3.0.0-beta.2"
log = "0.4"
simplelog = "^0.10.0"
tokio = { version = "^1.10", features = ["rt", "macros", "time", "process", "io-util", "fs"] }
notify = "^4.0"
